### ISSUE TITLE
Implement Search page

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#103]
We need to implement dedicated search page.

## Implementation:
- Url structure for search page would be `/search?q=term`
- Page structure
    - We can reuse the `PackageList` component to view data-packages
    - We have to create `Search` container for holding page state and components.

## Tasks:

- [ ] Create `Search` container
- [ ] Create search action and reducer
- [ ] Add search api to fetch data from backend
- [ ] Add Url structure to react router.

**Comment by subhankarb** [comment]
INVALID.
As we are move back from react to flask. So this page will be created in dpr-api. This issue will be handled by https://github.com/frictionlessdata/dpr-api/issues/221
