### ISSUE TITLE
Refactor Load of Data Package Info and Data

### ISSUE THREAD

**Issue by rufuspollock** [datopian/frontend-showcase-js#106]
At the moment the Data Package info and data loading is a bit messy - we did some hacks to work around brokenness in datapackage-test, we also seemed to be confused about the structure of the data we stored and the structure of the Redux store cache for this.

## Tasks

* [x] Revert hacks for datapackage-js library issues - #88 
* [x] Load data in structure we need elsewhere esp in views (remove the adding and removing of headers we do)
* [ ] Structure Redux store as we want it
* [ ] Test this all properly

**Comment by rufuspollock** [comment]
NOTE: redux refactor will no longer really be needed since it is obsoleted by simplification in data loading.

**Comment by rufuspollock** [comment]
DUPLICATE / FIXED in #109 and in commit 2f1ec38aed8d7bcce7ff0cd39d531884eeec380a (to add data loading).
