### ISSUE TITLE
Support vega / vega-lite as input view spec types

### ISSUE THREAD

**Issue by rufuspollock** [datopian/frontend-showcase-js#107]
At the moment, I've discontinued vega / vega-lite spec support as it is not on the critical path. (Strictly discontinued is a bit strong: the current support was of dubious solidity and focused on vega-lite).

What we need to do: add support back

## Acceptance criteria

- [ ] we do support both vega and vega-lite

## Tasks

* [ ] Define spec for "DP Vega", "DP Vega Lite"
* [x] Implement  DP Vega -> Vega - https://github.com/frictionlessdata/dpr-api/issues/309
* [ ] Implement DP Vega Lite -> Vega Lite -> Vega

**Comment by anuveyatsu** [comment]
Currently, we support `vega` spec input, but not `vega-lite` - so this issue remains open.
