### ISSUE TITLE
Remove code obsoleted by reversion to MPA

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#111]
We added some code when we were trying to migrate to react. But now we revert back to MPA (dpr-api). So we now do not need some of that code.

Action: Remove the unneeded code created when trialling MPA.

## Tasks

* [x] Analyse what we need to remove (see below)
* [x] Remove code and associated tests
* [x] Check all tests passing

Current `src/` directory analysis (also remove all corresponding tests)

```
├── actions
│   ├── datapackageActions.js
│   └── publisherPageAction.js    # remove
├── api
│   ├── dataPackagePageApi.js
│   └── publisherPageApi.js         # remove
├── components                             # remove everything EXCEPT dataPackageView
│   ├── HomePage.jsx
│   ├── NotFoundPage.jsx
│   ├── common
│   │   ├── PackageList.jsx
│   │   └── PackageListItem.jsx
│   ├── dataPackageView
│   │   ├── DataDisplayPanel.jsx
│   │   ├── DataDisplayPanelItem.jsx
│   │   ├── HandsOnTable.jsx
│   │   ├── PlotlyChart.jsx
│   │   └── VegaLiteChart.jsx
│   ├── footer
│   │   ├── Footer.css
│   │   └── Footer.jsx
│   ├── navbar
│   │   ├── NavBar.css
│   │   ├── NavBar.jsx
│   │   └── brand-small-logo.png
│   └── publisherPage
│       └── PublisherDetails.jsx
├── constants
│   └── actionTypes.js                       # remove *some* stuff
├── containers
│   ├── App.jsx                                    # remove
│   ├── DataPackageView.jsx
│   └── PublisherDetailsPage.jsx      # remove
├── index.jsx
├── reducers
│   ├── datapackageReducer.js
│   ├── index.js
│   └── publisherPageReducer.js     # remove
├── routes.jsx                                      # remove (?)
├── store
│   └── configureStore.js                  # remove *some* stuff (?)
├── utils
│   └── view.js
└── webpack-public-path.js              # remove
```
