### ISSUE TITLE
Show views as soon as their data is available

### ISSUE THREAD

**Issue by rufuspollock** [datopian/frontend-showcase-js#118]
When there are multiple resources we need to fetch them all and it may take a lot of time. To enhance UX we could show graphs and tables as soon as their data is available.

### Context and problems

> To update the properties of an existing component, you call render again with a new element. If you call ReactDOM.render a second time to update properties, all your props are completely replaced. ([React documentation](https://facebook.github.io/react/blog/2015/10/01/react-render-and-top-level-api.html))

> There is no big difference when you have a few components, but when your app grows large, re-rendering from the top is going to introduce a slowdown. ([post by Dan Abramov](http://stackoverflow.com/questions/35281459/re-rendering-an-app-using-reactdom-render-rather-than-within-its-container-com))

In our case so far we do not have lots of components. So maybe at this point it is appropriate to use re-rendering from `index.jsx`.

## Analysis

1. As soon as `datapackage.json` is fetched first rendering happens.
2. Then fetch all resources one by one.
3. After fetching each resource re-render appropriate component.

## Tasks

Overall estimate: 5h

* [x] update `index.jsx` using snippet below for incremental loading and indicating load process [2h]
  * [x] use code snippet below
* [x] refactor `MultiViews.jsx` [1.5h]
  * [x] have `componentWillReceiveProps()` method for handling updated props
  * [x] handle loading indicator
  * [x] fix tests
* [x] refactor `HandsOnTable.jsx` [1.5h]
  * [x] have `componentWillReceiveProps()` method for handling updated props
  * [x] handle loading indicator
  * [x] fix tests

## Acceptance criteria
* [x] Showing loading indicators whilst waiting for data to load
* [x] Incrementally load data resources and show data as soon as relevant data is loaded
 
---
```javascript=
// index.jsx

let dp = await new Datapackage(DATA_PACKAGE_URL)

let divElements = document.querySelectorAll('.react-me')

divElements.forEach((el, idx) => renderComponentInElement(el, idx-1, true))
    
// get the resource data one by one
Promise.all(dp.resources.map(async (resource, idx) => {
  // we assume resource is tabular for now ...
  const table = await resource.table
  let rowsAsObjects = false 
  resource.descriptor._values = await table.read(rowsAsObjects)
  
  // only re-render MultiView if this resource is used in one of the views there
  // we expect views object to have name attribute that refers
  // to a resource. If not, it refers to the first resource.
  {
    name: ...
    resources: [ ]
  }
  dp.views.forEach(view => {
    if((!view.name && idx === 0) || (view.name === resource.descriptor.name)) {
      renderComponentInElement(divElements[0])
    }
  })
  // here we re-render a table for which data is loaded 
  // in this iteration
  renderComponentInElement(divElements[idx+1], idx)
}))

// To indicate that data is loading we can have 3rd argument 
// "loading" that is by default set to false. 
// So in the first rendering we set it to true, and 
// when data is fetched and we re-render a component, 
// nothing is passed so it's false.
function renderComponentInElement(el, idx, loading=false) {
  if (el.dataset.type === 'resource-preview') {
    let compiledView = compileView(...)
    // test if rows = 0 and show loading symbol if so ...
    // render the table a bit (just headings ...)
    ReactDOM.render(<HandsOnTable spec={compiledView} idx={idx} />, el);
  } else if (el.dataset.type === 'data-views') {
    ReactDOM.render(<MultiViews dataPackage={dp} />, el);
  }
}
```
