### ISSUE TITLE
[epic] Refactor so graph and tables can be separated in rendered page

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#119]
The Data Package view page should look like http://data.okfn.org/data/core/co2-ppm. In this page graph at top is separated from data table previews and data table is populated after the description of each table. 

Currently, there is one monolithic React container called `DataPackageView` that renders the graph and all tables. This can only render them contiguously in the DOM so we can't do this.

We need to refactor the dpr-js so we can have graphs and tables separately. We also need to have a clear method for connecting between the backend (which layouts out the HTML) and the JS code here. (e.g. dpr-api generate blank div with class name containing resource id e.g. `<div class="resource-{idx}"></div>` and then dpr-js hooks onto those and renders)

## Tasks

* [x] Research using react for parts of the page not all of it - #120 
* [x] Agree how we want the setup to work so we can support what we want now and have flexibility going forward
  * e.g. how do we want to handle multiple views -- do we have a switcher or just lay them out one after another? ANS: do simplest thing possible for now.
* [x] Implement https://github.com/frictionlessdata/dpr-js/issues/126

## Acceptance

* [x] Can render all our current core to look like the old site
* [x] Handles multiple views
* [x] Handles multiple resources e.g. http://data.okfn.org/data/core/co2-ppm

## data.okfn.org layout

![image](https://cloud.githubusercontent.com/assets/180658/23598887/a8df88c6-023d-11e7-9d52-85cfde74f9be.png)

**Comment by rufuspollock** [comment]
Removed #118 out of this as not really part of this.

**Comment by anuveyatsu** [comment]
FIXED last changes in https://github.com/frictionlessdata/dpr-js/pull/134
