### ISSUE TITLE
[research] Using React for parts of a page - not all of it

### ISSUE THREAD

**Issue by rufuspollock** [datopian/frontend-showcase-js#120]
At the moment, we just render one big React container into the page at one element mount point. Going forward (see e.g. #119) we want to render react components in different parts of the page -- but not have the whole page as a React app.

## Tasks

* [x] Research online existing solutions
* [x] Write them up in a short recommendation

## Acceptance criteria

* [x] Is it possible to use react this way [YES]
* [x] What is best practice / best approach for doing this
  * Come up with recommended changes and approach going forward
  * e.g. are there conventions like using particular class or id for backend to use that this frontend can recognize (and where we can auto pass data ...)

## Recommendation: How Backend and Frontend Communicate

*This will be copied into index.jsx*

From the back-end we expect a template to have `div` elements with specific `class` and `data-type` attributes:

* To tell a front-end that a given `div` element is for React component, it should have `class=react-me`.
* To tell a front-end which component to render in that `div` element, it should provide `data-type` attribute - `resource-info` for HandsOnTable and `data-views` for the graphs.
* Also any properties can be passed from the back-end using `data-*` prefix. 

```htmlmixed=
# backend html

<div class="react-me" data-type="resource-preview" data-abc={...} />

// types
resource-preview
data-views
```

```javascript=
// frontend index.jsx

import MultiViews from './...';
import HandsOnTable from './...';


function renderComponentInElement(el) {
  const props = Object.assign({}, el.dataset);
  
  if (el.dataset.type === 'resource-preview') {
    ReactDOM.render(<HandsOnTable {...props} />, el);
  } elseif (el.dataset.type === 'data-views') {
    ReactDOM.render(<MultiViews {...props} />, el);
  }
}

document
  .querySelectorAll('.react-me')
  .forEach(renderComponentInElement)

```

**Comment by rufuspollock** [comment]
I've found the following useful.

## Using React in a multi-page app [SO]

http://stackoverflow.com/questions/31933359/using-react-in-a-multi-page-app

This has a full answer plus a good recommended approach which I inline here from the accepted answer. The only changes I'd make is to avoid using html ids to identify React components (ids are supposed to be unique) and to standardize on some way to pass parameters.

```
import CommentBox from './apps/CommentBox';
import OtherApp from './apps/OtherApp';

const APPS = {
  CommentBox,
  OtherApp
};

function renderAppInElement(el) {
  var App = APPS[el.id];
  if (!App) return;

  // get props from elements data attribute, like the post_id
  const props = Object.assign({}, el.dataset);

  ReactDOM.render(<App {...props} />, el);
}

document
  .querySelectorAll('.__react-root')
  .forEach(renderAppInElement)
```

---

```
<div>Some Article</div>
<div id="CommentBox" data-post_id="10" class="__react-root"></div>

<script src="/all.js"></script>
```

## Is React suitable for one-off components in non-SPA websites? [Reddit]

https://www.reddit.com/r/reactjs/comments/4b18k2/is_react_suitable_for_oneoff_components_in_nonspa/

Ans: yes you can. Though they don't give specific approaches. (They mention react-rails for rails)

> ... is react suitable for one-off components - for basically adding a "nice" layer on top of a rendered backend? I feel like I am trying to smash two different concepts together but I do really like the "reasoning" about the state of an app/site with React, and hopefully can simply apply that down to just a component level.

### Libraries

Found this existing lib. However, think a library here is probably overkill given the simplicity of what is needed.

https://github.com/noderaider/react-dom-inject

**Comment by anuveyatsu** [comment]
_Using the examples above we can adapt them for our case:_
From the back-end we expect a template to have `div` elements with specific `class` and `data-type` attributes:
* To tell a front-end that a given `div` element is for React component, it should have `class=react-me`.
* To tell a front-end which component to render in that `div` element, it should provide `data-type` attribute - `resource-info` for HandsOnTable and `data-views` for the graphs.
* Also any properties can be passed from the back-end using `data-*` prefix. 

```htmlmixed=
# backend html

<div class="react-me" data-type="resource-info" data-abc={...} />
```

```javascript=
// frontend index.jsx

import MultiViews from './...';
import HandsOnTable from './...';


function renderComponentInElement(el) {
  const props = Object.assign({}, el.dataset);
  
  if (el.dataset.type === 'resource-info') {
    ReactDOM.render(<HandsOnTable {...props} />, el);
  } elseif (el.dataset.type === 'data-views') {
    ReactDOM.render(<MultiViews {...props} />, el);
  }
}

document
  .querySelectorAll('.react-me')
  .forEach(renderComponentInElement)

```

**Comment by rufuspollock** [comment]
FIXED. See recommendation in the issue description (minor rework of @anuveyatsu comment 2h ago).
