### ISSUE TITLE
Implement views and resource previews separate in rendered page

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#126]
At the moment all the components are rendered together inside a single `div` element. However, we need them to be separate as we have pre-rendered elements in between them. To implement it we need to render each component into different html elements using `ReactDOM.render` several times.

Part of #119 

## Tasks

Estimate: 7h

* [x] Update `index.jsx` [3h]
  * [x] ~~Update test (if we have one)~~
  * [x] Mockup html page
  * [x] Load data in the beginning (datapckage-js)
  * [x] Render components (use snippets above)
* [x] Refactor `DataPackageView.jsx` -> `MultiView.jsx` to use with updated `index.jsx` [3h]
  * [x] receives descriptor (with raw data in it), then renders a graph (or graphs)
  * [x] should be able to render multiple graphs (one by one)
* [x] Refactor `HandsOnTable.jsx` to use with updated `index.jsx` [1h]
  * [x] receives raw data and gets specs for the table
* [x] Document how backend and frontend communicate in index.jsx

## How Backend and Frontend Communicate

*This will be copied into index.jsx*

From the back-end we expect a template to have `div` elements with specific `class`, `data-type` and `data-resource` attributes:

* To tell a front-end that a given `div` element is for React component, it should have `class=react-me`.
* To tell a front-end which component to render in that `div` element, it should provide `data-type` attribute - `resource-preview` for HandsOnTable and `data-views` for the graphs.
* To tell a front-end which resource to render, it should provide `data-resource` attirbute with index of resource or name.
* Also any properties can be passed from the back-end using `data-*` prefix. 

```htmlmixed=
# backend html

<div class="react-me" data-type="resource-preview" data-abc={...} />

// types
resource-preview
data-views
```

```javascript=
// frontend index.jsx

import MultiViews from './...';
import HandsOnTable from './...';


function renderComponentInElement(el) {
  const props = Object.assign({}, el.dataset);
  
  if (el.dataset.type === 'resource-preview') {
    ReactDOM.render(<HandsOnTable {...props} />, el);
  } elseif (el.dataset.type === 'data-views') {
    ReactDOM.render(<MultiViews {...props} />, el);
  }
}

document
  .querySelectorAll('.react-me')
  .forEach(renderComponentInElement)

```

**Comment by rufuspollock** [comment]
Bugs / improvements:

* Support for setting resource id / name in resource-preview
* Bug: if you try this with no views in the data package it fails (need a small test for this if possible as a common situation!)

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/131

**Comment by rufuspollock** [comment]
@anuveyatsu one last thing we missed! We should display the view `title` attribute above each view  as a title (in the old days we had it in the switcher button but now we are just displaying one after another).

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/134
