### ISSUE TITLE
datapackage with zero views failing to load

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#139]
Right now we assume that all datapackage have at least one view component. But in geojson datapackage there are no view components. 
So loading of geojson data is failing. And also `LeafletMap` component is not prepared for incremental data loading.

## Tasks

- [x] Add test for datapackage which does not have any view component.
- [x] Added check for undefined views in index.jsx.
- [x] Add function `componentWillUpdate` in `LeafletMap` component.

**Comment by anuveyatsu** [comment]
This issue actually does **two** things which are distinct:
* When there are no views provided in a datapackage, it fails to render components because we try to iterate over `views` object. So we needed to add if clause to check if there are any views (and have a test for it).
* LeafletMap component refactored to be able to handle re-rendering when new props come.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/140
