### ISSUE TITLE
Vega support for DPR

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#142]
As a Publisher I want to add sophisticated graphs (using Vega) to my data package so that others can see how cool the data is.

## Tasks

* [x] create a demo datapackage with Vega views - use http://vega.github.io/vega-editor/?mode=vega&spec=barley and publish it
* [x] in `MultiViews` have a new case when `specType=vega`
* [x] create `VegaChart.js` component for rendering vega graph (must be similar to `PlotlyChart`)

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/143
