### ISSUE TITLE
Support for multiple resources per a single view

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#144]
At the moment the code can handle as many views but only if they use a single resource. E.g.:
```
"views": [
  {
    "name": "some-unique-name",
    "title": "some view",
    "resources": [0],
    "specType": "simple", // or can be "vega" now if using vega spec
    "spec": {
      ...
    }
  }
]
```

But if a view uses more than 1 resource it is not supported at the moment, e.g. `"resources": [0, 1]`

## Tasks

* [x] find example with more than 1 resource per view https://vega.github.io/vega-editor/?mode=vega&spec=lifelines
* [x] new function in utils to check if all resources are loaded
* [x] new function in utils to build data for Vega
* [x] update tests for MultiViews
* [x] have new tests for new functions

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/145
