### ISSUE TITLE
Vega data transforms support

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#148]
Currently, we are not having a `data` property in the DP Views specType `vega` spec -- we generate this property from the Data Package View `sources`.

Note that data is loaded using datapackage-js library so in Vega spec all values are inlined.

We could keep `data` property in Vega spec and remove `name`, `url`, `source` properties. This way we can keep `transform` property in the spec and it can be used later when building a graph. For example:

```javascript=
  // vega 
  "data": [
    {
      "name": "jobs",
      "url": "data/jobs.json",
      "transform": [
        {
          "type": "stack",
          "groupby": ["year"],
          "field": "perc",
          "sortby": ["-job", "-sex"]
        }
      ]
    },
    
    // dp views with vega spec type
    // 
    resources: [
      {
        "path": ...
        "name": "jobs"
      }
    ]
    "spec": {
      "data": [
        {
          "name": "jobs"
          "transform": ...
        }
      ]
    }
    
for dataItem in vegaSpec.data:
  relevantResource = resources.findByName(dataItem.name)
  Object.assign(dataItem, { values: resources[]
  
  
// In code
if no data attribute on vega:
  // just copy all the resources as vega data entries ...
```

Overall, for Vega graph spec our views would look like following. All datasets must be specified in `resources` property of the descriptor as before, but we would not have `resources` reference property inside `views`:

```json=
{
  "views": [
    {
      "name": "view-name",
      "title": "view-title",
      "specType": "vega",
      "spec": {
        "data": [
          {
            "name": "name-of-dataset-for-reference",
            "transform": {},
            "anotherOperation": {}
          }
        ],
        "allOtherSpec": {}
      }
    }
  ]
}
```

No `data` attribute inside `spec` would mean to use all resources in the given order.

## Tasks

* [x] do analysis and update this description
* [x] refactor current code to work with `data` attribute inside vega spec
  * [x] refactor `utils`
  * [x] refactor `MultiViews`
* [x] have this example working: http://vega.github.io/vega-editor/?mode=vega&spec=choropleth
* [x] have this example working: https://vega.github.io/vega-editor/?mode=vega&spec=airports

**Comment by anuveyatsu** [comment]
From hackmd by Rufus:

```json=

resources: [
  {
    "name": "airports",
    ...
  }
]
spec: {
  data: [
    {
      "name": "airports",
      // no source here!!
      
      // may have transform or not ...  
    }
    {
      "name": "xyz",
      "source": "airports",
      "transform": "abc"
    }
  ]
}
```

```json=
view...

resources: [ { "name": "routes" ...}]

...

"data": [
  {
    "name": "routes,
    // no transform or anything ...
  }
  {
    "name": "states",
    "url": "data/us-10m.json",
    "format": {"type": "topojson", "feature": "states"},
    "transform": [
      {
        "type": "geopath", "projection": "albersUsa",
        "scale": 1200, "translate": [450, 280]
      }
    ]
  },
  {
    "name": "traffic",
    "source": "routes",
    "transform": [
      {
        "type": "aggregate", "groupby": ["origin"],
        "summarize": [{"field": "count", "ops": ["sum"], "as": ["flights"]}]
      }
    ]
  },
  {
    "name": "airports",
    "url": "data/airports.csv",
    "format": {"type": "csv", "parse": "auto"},
    "transform": [
      {
        "type": "lookup", "on": "traffic", "onKey": "origin",
        "keys": ["iata"], "as": ["traffic"]
      },
      {
        "type": "filter",
        "test": "datum.traffic != null"
      },
      {
        "type": "geo", "projection": "albersUsa",
        "scale": 1200, "translate": [450, 280],
        "lon": "longitude", "lat": "latitude"
      },
      {
        "type": "filter",
        "test": "datum.layout_x != null && datum.layout_y != null"
      },
      { "type": "sort", "by": "-traffic.flights" },
      { "type": "voronoi", "x": "layout_x", "y": "layout_y" }
    ]
  },
```

**Comment by anuveyatsu** [comment]
FIXED 
mainly in https://github.com/frictionlessdata/datapackage-render-js/commit/b1493b1eeea463856064050782f2f82bfa2d463d
and also in https://github.com/frictionlessdata/dpr-js/pull/151
