### ISSUE TITLE
Factor out the spec manipulation work into datapackage-render-js

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#150]
Move all functions from `utils/view.js` to https://github.com/frictionlessdata/datapackage-render-js

```
Using this library in your own code
  
var dprender = import "datapackage-render"
var vega = import "vega"
  
// take a DP view and render to vega
var vegaspec = dprender.renderViewToVega(...)
vega.render(vegaspec)
  
var plotlyspec = dprender.renderViewToPlotly(...)
// error if this is vega type spec and we do not know how to conver
```
  
Bonus points for keeping cli.js and/or examples directory with e.g. rendering to png using this lib + vega https://github.com/frictionlessdata/datapackage-render-js/blob/master/cli.js

## Tasks

- [x] have a node module with utility functions (from current `utils/view.js`) in https://github.com/frictionlessdata/datapackage-render-js
- [x] install the package from github directly use `npm install --save git+https://git@github.com/frictionlessdata/datapackage-render-js.git`
- [x] replace all `viewutils` in the code with `dprender` and import from the installed package
- [x] delete `views.js` and corresponding tests
