### ISSUE TITLE
Implement ReactVirtualized for tables

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#153]
We'd like to implement a component for rendering tables using ReactVirtualized library.

## Analysis

Create similar React component to HandsOnTable for render a table using ReactVirtualized library.

> Note, size of react-virtualized may grow depending on included modules. Size below is from including basic modules for tables.

| Criteria          | react-virtualized       | handsontable                 |
|-------------------|-------------------------|------------------------------|
| build size(table) | ~120KB                  | ~570KB                       |
| documentation     | simple                  | a bit complicated            |
| React way         | Yes                     | No                           |
| Other             | Seems more customizable | Seems more strick and stable |

## Tasks

* [x] https://github.com/frictionlessdata/datapackage-render-js/issues/32
* [x] create `ReactVirtualized.jsx` component
  * [x] handles spec returned from dprender - with and without data
  * [ ] spinner when there is no data
* [x] refactor `index.jsx` to render ReactVirtualized instead of HandsOnTable

**Comment by anuveyatsu** [comment]
At the moment, react-virtualized renders table views for resources with some limitations:

- columns is not sortable - need some further work
- columns cannot be resized from the browser as it was in `handsontable` - the only way is having input fields where we can pass width of each column - not [supported by react-virtualized and no plans to](https://github.com/bvaughn/react-virtualized/issues/128)
- Copy and paste from the table to a spreadsheet does not seem to work very well (e.g. to google spreadsheet or excel)

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/154
see comment above for limitations of react-virtualized

**Comment by rufuspollock** [comment]
@anuveyatsu can you please make sure you do test this with excel / google spreadsheets and summarized properly the results. When that is done please close whilst also linking to a follow up issue about reverting to handsontable or fixing the key issues we have with react virtualized.

**Comment by anuveyatsu** [comment]
React-virtualized renders data in `div` elements, which leads to incorrect copy-pasting into Excel / Google Spreadsheet. It puts data in a single column because copied data has `\n` (new line) after each entry.

In Handsontable, data rendered in `table` element, which makes it possible to copy and paste values into Excel / Google Spreadsheet correctly as copied data is tab delimited (tsv).


We will revert table views to use Handsontable instead of React-virtualized in here - https://github.com/frictionlessdata/dpr-js/issues/155
