### ISSUE TITLE
Revert table views to use Handsontable instead of React-virtualized

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#155]
We need to revert from React-virtualized to Handsontable due to following reasons:

1) Columns cannot be resized - see more [here](https://github.com/frictionlessdata/dpr-js/issues/153#issuecomment-294115867)
2) Copy and paste from the table to a spreadsheet does not seem to work very well (e.g. to google spreadsheet or excel) - see more [here](https://github.com/frictionlessdata/dpr-js/issues/153#issuecomment-294523713)

## Tasks

* [x] refactor `index.jsx`
  * [x] to instanciate `Handsontable` not `ReactVirtualized`
  * [x] to build appropriate spec

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/156
