### ISSUE TITLE
Try out direct usage of Vega Dataflow from node / JS

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#157]
We need to test Vega Dataflow library in DPR-JS to see how we can use it for our needs:

* transforming resources prior rendering views

## Acceptance criteria

* [x] List of transforms that we need
* [x] Example usage of each transform in a list
* [x] Specifications on how to use it

## Tasks

* [x] Make a list of transforms that can be integrated into our project
* [x] Try out each transform and keep examples in hackmd pad / gist
* [x] Suggest instructions on how to use it from datapackage.json

## Analysis

Please see https://hackmd.io/JwEwjGDMCGBMsFoBsAWAHJBLhmggRgAzCbDDRkgCsAZgKaw35A==?both#vega-dataflow-usage-for-dp-views

**Comment by anuveyatsu** [comment]
@rufuspollock can you review my analysis here: https://hackmd.io/JwEwjGDMCGBMsFoBsAWAHJBLhmggRgAzCbDDRkgCsAZgKaw35A==?both#vega-dataflow-usage-for-dp-views

**Comment by anuveyatsu** [comment]
@rufuspollock I have analysed usage of Vega transforms and the outcome is that we could use some of them in the DataHub. These transforms would be suitable for our usage:

- Aggregate
- Filter
- Formula
- Sample

Here is how it would suit in `dp.json` - https://hackmd.io/JwEwjGDMCGBMsFoBsAWAHJBLhmggRgAzCbDDRkgCsAZgKaw35A==?both#suggestion-on-usage-from-datapackagejson

There is more analysis in details here https://hackmd.io/JwEwjGDMCGBMsFoBsAWAHJBLhmggRgAzCbDDRkgCsAZgKaw35A==?both#vega-dataflow-usage-for-dp-views

**Comment by anuveyatsu** [comment]
I'm closing this issue for now. We will open a new one for implementation of this in DataHub.
