### ISSUE TITLE
Render table if in a view the spec type is "table"

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#159]
In `views` property, publishers can define different `specType` to render different graphs. At the moment, allowed spec types are simple and vega and both render charts. However, we want publishers to be able to define `specType` as `table` and render a table.

## Acceptance criteria

* [x] can define `specType = "table"` and get a table as a view

## Tasks

* [x] refactor `MultiViews` container to have a case when `specType='table'`
* [x] update tests and snapshot

## Analysis

Take a look at `MultiViews.jsx` container.

**Comment by anuveyatsu** [comment]
FIXED in #160
