### ISSUE TITLE
Error when there is no format or extension for a resource

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#165]
In the frontend we are getting following error when there is no format/extension for resources:

```bash
# in https://testing.datahub.io/core/cofog
Uncaught (in promise) TypeError: Cannot read property 'includes' of undefined
    at renderComponentInElement (https://testing.datahub.io/static/dpr-js/dist/bundle.js:101914:33)
```

## Acceptance criteria

Following packages are working on the live site:
* [x] https://testing.datahub.io/core/cofog
* [x] https://testing.datahub.io/core/cpi
* [x] https://testing.datahub.io/core/currency-codes

## Tasks

* [ ]
