### ISSUE TITLE
[GeoJSON] Leaflet map is erroring + cannot initialize more than one map container

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#167]
For some reason leaflet maps are not rendered with the error message:

```
bundle.js:207 TypeError: Cannot read property 'hoverText' of null
```

We are getting the following error when there is more than 1 map container:
```
Uncaught (in promise) Error: Map container is already initialized.
```

E.g., https://datahub.io/core/geo-nuts-administrative-boundaries

## Acceptance criteria

* [x] leaflet maps are rendered as expected
* [x] several maps are also rendered on the single showcase page

## Tasks

* [x] Investigate the source of the issue
* [x] Fix the issue and re-build the bundle
* [x] update frontend and deploy

## Analysis

The error message refers to `hoverText` variable in the code, which was introduced with embeddable views. By taking a look into it, we've identified that it is unable to update a state of the react component. The solution here would be to add a constructor method that will have an initial state.

Rendering multiple maps is fixed probably due to `leaflet` map package updates.

**Comment by rufuspollock** [comment]
@anuveyatsu any idea what the issue is here and whether you have a fix?

**Comment by anuveyatsu** [comment]
FIXED see https://datahub.io/examples/geojson-tutorial
