### ISSUE TITLE
Preview for large datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#168]
Since we have preview version of tabular resources, which are in JSON format, we need to refactor resource loading logic and rendering components logic.

## Acceptance criteria

* [x] previews gets rendered using preview-resources (if exist)
* [x] if there is no preview-resource then it will work with original one

## Tasks

* [x] refactor `src/index.jsx`
  * [x] iterate and render normal views
  * [x] render preview views
* [x] refactor MultiViews
  * [x] ignore preview views

## Analysis

What's the frontend algorithm:

* Views at top of page:
  * iterate through `views`
    * ignore those views which are datahub/type/preview
  * Go to: render view ...
* Previews:
  * Search views for datahub/type/preview and resources: [{myname}]
  * Then go to renderView
* Render view:
  * locate the generated resource for this view: search resources for resource with datahub/forView.contains('my view name')
    * If does not exist: proceed as normal ... (do transformation in frontend)
  * Use that resource (no more local transformation and compilation ??)

```html
<div class="file-preview" data-showcase-handler="preview" data-resource-id="1"></div>

<div id="resource-{{loop.index - 1}}" class="react-me tables part"
             data-type="resource-preview" data-resource="{{ loop.index - 1 }}"></div>
```

Javascript

```
// find all the react-me and data-type resource-preview

1. locate the "preview" view for this resource
2. render that view

// 1. Locating the preview view

findPreviewViewForResource(resourceName) {
  ...
}
1. Search views for datahub.type=preview and resources: [{myname}]

// 2. rendering views
renderView(view) {
  return 
}
1.locate the generated resource for this view: search resources for resource with datahub/forView.contains('my view name')
2. If (exists): ...
   * TRUE: 
   * FALSE: proceed as we used  to ... (do transformation in frontend)
3. Use that resource (no more local transformation and compilation ??)

```

Old system

```mermaid
graph LR

raw[Raw View] --> compileres
compileres[compile in resource] --> compilein
compilein[compile in data<br/>Inline resource+transform] --> spec
spec[Generate ploty spec] --> end1
end1[html +js] --> end2[svg]
```

New system

```mermaid
graph LR

raw[Raw View] --> compileres
compileres["Compile in resource<br/>Use the 'forview' resource"] --> compilein
compilein["compile in data<br/>Inline resource data (no transform)"] --> spec
spec[Generate plotly] --> end1
end1[html +js] --> end2[svg]
```

Algorithm for views at top of page (non-preview views!)

```javascript
for(view of pkg.views) {
  if (view.datahub && view.datahub.type === 'preview') {
    // skip ...
  }
  return renderView(view) // returns a react object ... that you can add to your MultiView object
}
```

**Comment by anuveyatsu** [comment]
FIXED
