### ISSUE TITLE
Upgrade to Vega v3

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#169]
Since Vega v3 is now stable and authors seem to focus on that version (docs and examples are around v3 now), we want to upgrade our showcase-frontend-js library to use it.

## Acceptance criteria

* [x] Graphs are working with Vega 3 specs
* [x] All old example vega datasets are working

## Tasks

* [x] Upgrade Vega version in `frontend-showcase-js` library (currently using 2.6.5) to 3.x.x
* [x] Setup Vega v3 - see analysis
* [x] Update example vega datasets by replacing old specs with new one (just copy over from examples as those datasets are already there - https://vega.github.io/editor/#/examples/vega/timelines)

## Analysis

We don't need to follow porting guide v2 => v3 as vega has updated specs for all 3 example datasets we're using. So just need to copy over.

After installing Vega v3, we need to do number of debuggings/refactorings as it seems modules in v3 work differently. We can simply try out with new specs:

* create a new example dataset using new specs from vega v3
* test it out with installed vega v3
* if errors - debug/refactor

**Comment by anuveyatsu** [comment]
FIXED - see https://datahub.io/examples/vega-views-tutorial-grouping
