### ISSUE TITLE
Show full name when hovering preview table's headings

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#170]
As a User, I want to hover over headings in the preview table and see its full name so that I can read all headings even if they're too long or data has lots of columns.

## Acceptance criteria

* [ ] when I hover over preview table's heading I can see full name

## Tasks

* [ ] read docs of handsontable re how to do this
* [ ] implement the fix
* [ ] deploy

## Analysis

In preview table on hover on headings, it should display full name of heading:

<img width="1280" alt="screen shot 2017-10-16 at 11 15 29" src="https://user-images.githubusercontent.com/17809581/31604395-6c6f3784-b263-11e7-94ff-c4b86d406417.png">

**Comment by zelima** [comment]
Moving to backlog for now as @anuveyatsu is away

**Comment by zelima** [comment]
We should just include `headerTooltips: true` in handsontable properties https://docs.handsontable.com/pro/6.0.1/demo-header-tooltips.html
