### ISSUE TITLE
When reading files use data.js instead of tableschema

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#171]
We need this as tableschema-js does not allow using local paths in browsers - https://github.com/frictionlessdata/tableschema-js/blob/15a67461974c555ced76e296e46a1cf15df8eefb/src/helpers.js#L31-L33 and we want to re-use bundle.js in Electron app. As Electron app is actually uses browser window, tableschema not allowing reading files from local paths.

## Acceptance criteria

* [x] frontend still works as before
* [x] electron app works with bundle.js

## Tasks

* [x] refactor `/src/utils/datapackage.js` to use data.js library

**Comment by pwalsh** [comment]
@anuveyatsu 

Why not do a PR on tableschema?

**Comment by anuveyatsu** [comment]
@pwalsh that's just matter of time - not sure how long it would take to do a PR on tableschema, while data.js is ready to use. However, I will open an issue in tableschema to get the reason why it is not available in browser.

**Comment by rufuspollock** [comment]
@pwalsh in general i think that tableschema should not handle loading of files etc -- that can be encapsulated elsewhere e.g. data.js (o/w we have to support all the loading stuff across different libs). Thus, i'm happy to have loading happening here via data.js.

**Comment by anuveyatsu** [comment]
FIXED - minor changes just for Electron app

**Comment by anuveyatsu** [comment]
After several trials, the best way to read data is to check if it is inlined. This way, we can read files in Electron before rendering the page, which allows us to do not mess with in browser support. Otherwise, we need to have workarounds for `fs` module that is used in upstream libraries, e.g., `data.js`.

**Comment by rufuspollock** [comment]
@anuveyatsu i'm not sure if i understand what you mean by "inlined". How would this work if i open a 1Gb CSV - would it crash the electron app?
