### ISSUE TITLE
Refactor to use Redux and better separation of components

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#40]
* [x] add new components (plotly, vega, and handsontable) that just do those things with no data package knowledge or logic - #41 
* [x] datapackage.js - use the library for loading datapackage and resources #42 
* [x] redux - introduce central store for DataPackage and resources #43
* [x] add container components as "controllers" for entire app. Do 3 things
  * [x] Turn DP views into actual graphs building children React presentational components (e.g. turn recline spec into plotly spec)
  * [x] convert data from raw form into correct form for subcomponents
  * [x] Kick off data loading (if that is still needed in redux world)
* [x] refactor index.js to pass DOM elements and config data into the container components

**Comment by anuveyatsu** [comment]
FIXED last PR https://github.com/frictionlessdata/dpr-js/pull/63
