### ISSUE TITLE
Publisher Page

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#53]
Original User story:
As a Consumer I want to see a publisher’s profile so that I can discover their packages and get a sense of how active and good they are 

As a Publisher I want to have a profile with a list of my data packages so that:
- Others can find my data packages quickly and easily
- Can see how many data packages i have
- **I can find a data package i want to look at quickly [they can discover their own data]**
- **I can find the link for a data package to send to someone else**

Tasks flow:
- [x] Create publisher details component #60 
- [x] Create Package List item component #54 
- [x] Create Publisher Page container #55 
- [x] Create Mock api to populate data to dashboard container #56 
- [x] Add route to map url to Dashboard Container #57 
- [x] Use REST API to get data from backend #58 

New Task:
- [x] Convert React to HTML pages https://github.com/frictionlessdata/dpr-api/issues/222

Acceptance Criteria:
- [x] When goto {baseurl}/{publisher name} publisher page will show
- [x] Publisher page will load all data packages and publisher details
- [x] While clicking package preview, should redirect to data package page.

**Comment by subhankarb** [comment]
FIXED.
All subtasks completed

**Comment by rufuspollock** [comment]
Plus note that most of this moved back into the server as part of https://github.com/frictionlessdata/dpr-api/issues/222
