### ISSUE TITLE
Add basic utilities and refactor to have whole site in React

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#67]
### Tasks:
- [x] Change test framework from Ject to mocha. [going with jest]
- [x] Add lint
- [x] Change webpack to load css and other for bootstrap.
- [x] Add different webpack and store configuration for dev and prod
- [x] Add travis settings for build
- [x] Remove bundle.js from build to generate while deploying. This process will happen in deploy time.

- [x]  Merge DataPackageViewContainer with TabularResourceViewContainer and call it DataPackageViewContainer
- [x] Refactor methods for generating specs for Plotly, Vegalite, Handsontable:
  - [x] It should take list of resource data and return list of specs

**Comment by subhankarb** [comment]
Tried to change from jest to mocha. But handsontable testing was giving problem. And could not found any solution for it. Going with mocha for now.

**Comment by rufuspollock** [comment]
FIXED in PR #76
