### ISSUE TITLE
Create publisher meta data component

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#75]
### Description
This component should take `data` object as props and render publisher meta data that contains following:
* date when joined
* contact info (if provided): country, email, phone
* gravatar

### Step-by-step implementation
* [ ] Create PublisherMetaData presentational component
* [ ] Render div element with publisher contact details, joined date, etc.
* [ ] Have if statement for cases when publisher did not provide contact details or it is private

### Acceptance criteria
* [ ] Render component with publisher meta data
