### ISSUE TITLE
DP Views implementation status and documentation

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#83]
What is the state of support in DPR-JS for the various different DP views options? Also, let's provide some initial docs for third parties on how they can specific DP views for use in DPR-JS.

## Tasks

* [x] Fill out [DP views implementation status spreadsheet][sheet] with implementation status
* [x] Example datapackage.json for views - how do the work in standard cases
* [x] **How** do we test different combinations (in automated way) (NOTE: this is **how** not requesting implementation yet)

[sheet]: https://docs.google.com/a/atomatic.net/spreadsheets/d/161rgtX3q34vIDbbfdCdvhBO_3sDX2tcp7iX9dI1Acj8/edit?usp=drive_web

**Comment by anuveyatsu** [comment]
@rufuspollock Finished in hackmd pod. Need a review.

**Comment by rufuspollock** [comment]
@anuveyatsu could you list here the answer to the 3rd question - i.e. how you would go about testing this stuff comprehensively.

**Comment by anuveyatsu** [comment]
## Examples of `resources` attribute
Example of data resource - inline:
```
"resources": [
    {
      "name": "test",
      "data": [
        ["2014", 12, 0],
        ["2015", 13, -3],
        ["2016", 9, 1],
        ["2017", 14, -1]
      ],
      "schema": {
        "fields": [
          {
            "name": "date",
            "type": "string"
          },
          {
            "name": "autumn",
            "type": "integer"
          },
          {
            "name": "winter",
            "type": "string"
          }
        ]
      }
    }
  ]
```
Example of data resource - relative path:
```
"resources": [
    {
      "name": "test",
      "path": "data/test-data.csv",
      "format": "csv",
      "mediatype": "text/csv",
      "schema": {
        "fields": [
          {
            "name": "date",
            "type": "string"
          },
          {
            "name": "autumn",
            "type": "integer"
          },
          {
            "name": "winter",
            "type": "string"
          }
        ]
      }
    }
  ]
```
Example of data resource - URL:
```
"resources": [
    {
      "name": "test",
      "path": "https://url.com/data/test-data.csv",
      "format": "csv",
      "mediatype": "text/csv",
      "schema": {
        "fields": [
          {
            "name": "date",
            "type": "string"
          },
          {
            "name": "autumn",
            "type": "integer"
          },
          {
            "name": "winter",
            "type": "string"
          }
        ]
      }
    }
  ]
```

**Comment by anuveyatsu** [comment]
# Testing different combinations
All resource loading operations happen in Redux actions. So we can test different data source variations separately. To test it create a mock datapackage inside `__mocks__` folder. 

1. Create `mockresources` folder and inside create 3 datapackage json files with different data resources: inline, relative path, absolute url. Also create `data` folder here. Probably reuse examples above.
2. In `data` folder create test-data.csv file with some fixture data. For example:
```
date,autumn,winter
"2014",12,2,
"2015",13,3,
"2016",9,1,
"2017",14,1
```
3. Create test file in `__tests__/src/js/` - use this boilerplate and name it `resource.test.js`:
```javascript=
import 'babel-polyfill'
import configureMockStore from 'redux-mock-store'
import nock from 'nock'
import thunk from 'redux-thunk'
import * as actions from '../../../src/actions/datapackageActions'

const middlewares = [ thunk ]
const mockStore = configureMockStore(middlewares)

describe('how it works with different data sources', () => {

  afterEach(() => {
    nock.cleanAll()
  })

  it('should work with inline data source', async () => {
    nock('https://inline.com')
      .get('/datapackage.json')
      .replyWithFile(200, './__mocks__/mockresources/inline.json')

    const store = mockStore({ dp: {} })
    await store.dispatch(actions.getDataPackage(
      'https://inline.com/datapackage.json'
    ))
    let receivedResource = store.getActions()
    expect(0).toEqual(0) //replace with relative expect statements
  })

  it('should work with relative path for data source', async () => {
    nock('https://relative.com')
      .get('/datapackage.json')
      .replyWithFile(200, './__mocks__/mockresources/relativePath.json')
      .get('/data/test-data.csv')
      .replyWithFile(200, './__mocks__/mockresources/data/test-data.csv')

    const store = mockStore({ dp: {} })
    await store.dispatch(actions.getDataPackage(
      'https://relative.com/datapackage.json'
    ))
    let receivedResource = store.getActions()
    expect(0).toEqual(0) //replace with relative expect statements
  })

  it('should work with absolute URL for data srouce', async () => {
    nock('https://absolute.com')
      .get('/datapackage.json')
      .replyWithFile(200, './__mocks__/mockresources/absoluteUrl.json')

    nock('https://url.com')
      .get('/data/test-data.csv')
      .replyWithFile(200, './__mocks__/mockresources/data/test-data.csv')

    const store = mockStore({ dp: {} })
    await store.dispatch(actions.getDataPackage(
      'https://absolute.com/datapackage.json'
    ))
    let receivedResource = store.getActions()
    expect(0).toEqual(0) //replace with relative expect statements
  })

})
```
4. Now, to run these tests:
```
$ npm test resource.test.js
```
It will test if all differently specified data resources can be loaded correctly.

5. Next, we need to test if we can render loaded data with different graph types: vega-lite, plotly (and also handsontable). We already have these tests for recline view spec. To run them:
```
$ npm test DataPackageViewContainer.test.js
```

**Comment by rufuspollock** [comment]
FIXED.
