### ISSUE TITLE
External configuration

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#84]
The application should get configuration from external source so that we can configure this for different environment.

Solution: Make use of .env file and webpack DefinePlugin will pick it up and bundle the variable.

## Tasks:

- [ ] Add ```dotenv``` in dependency list.
- [ ] create `.env` file 
- [ ] Add webpack define plugin for both bev and prod build.

**Comment by rufuspollock** [comment]
INVALID / WONTFIX. I think we can just pass key variables in from the HTML and atm only thing we need is the `DATA_PACKAGE_URL` (see `index.html` for an example).
