### ISSUE TITLE
Comprehensive tests for DP view types & data sources

### ISSUE THREAD

**Issue by rufuspollock** [datopian/frontend-showcase-js#86]
*Follows on from analysis in https://github.com/frictionlessdata/dpr-js/issues/83*

When publishers write a data descriptor, they may use different data sources, e.g. inline, relative path and url. They also may use different spec for views, recline or vega-lite. We want to test all combinations (or as many as possible).

## Tasks

Tests for all combinations of:

* [ ] differently specified data sources:
  * [ ] inline
  * [ ] relative path
  * [ ] URL
* [ ] support for different graph types:
  * [ ] vega-lite (vega)
  * [ ] plotly
* [ ] support for handsontable

## Acceptance criteria

* [ ] tests for all combinations - may pass or fail. If there are failing tests, we create issues for them.

## Background Analysis - by @anuveyatsu 

All resource loading operations happen in Redux actions. So we can test different data source variations separately. To test it create a mock datapackage inside `__mocks__` folder. 

1. Create `mockresources` folder and inside create 3 datapackage json files with different data resources: inline, relative path, absolute url. Also create `data` folder here. Probably reuse examples above.

2. In `data` folder create test-data.csv file with some fixture data. For example:
```
date,autumn,winter
"2014",12,2,
"2015",13,3,
"2016",9,1,
"2017",14,1
```
3. Create test file in `__tests__/src/js/` - use this boilerplate and name it `resource.test.js`:
```javascript=
import 'babel-polyfill'
import configureMockStore from 'redux-mock-store'
import nock from 'nock'
import thunk from 'redux-thunk'
import * as actions from '../../../src/actions/datapackageActions'

const middlewares = [ thunk ]
const mockStore = configureMockStore(middlewares)

describe('how it works with different data sources', () => {

  afterEach(() => {
    nock.cleanAll()
  })

  it('should work with inline data source', async () => {
    nock('https://inline.com')
      .get('/datapackage.json')
      .replyWithFile(200, './__mocks__/mockresources/inline.json')

    const store = mockStore({ dp: {} })
    await store.dispatch(actions.getDataPackage(
      'https://inline.com/datapackage.json'
    ))
    let receivedResource = store.getActions()
    expect(0).toEqual(0) //replace with relative expect statements
  })

  it('should work with relative path for data source', async () => {
    nock('https://relative.com')
      .get('/datapackage.json')
      .replyWithFile(200, './__mocks__/mockresources/relativePath.json')
      .get('/data/test-data.csv')
      .replyWithFile(200, './__mocks__/mockresources/data/test-data.csv')

    const store = mockStore({ dp: {} })
    await store.dispatch(actions.getDataPackage(
      'https://relative.com/datapackage.json'
    ))
    let receivedResource = store.getActions()
    expect(0).toEqual(0) //replace with relative expect statements
  })

  it('should work with absolute URL for data srouce', async () => {
    nock('https://absolute.com')
      .get('/datapackage.json')
      .replyWithFile(200, './__mocks__/mockresources/absoluteUrl.json')

    nock('https://url.com')
      .get('/data/test-data.csv')
      .replyWithFile(200, './__mocks__/mockresources/data/test-data.csv')

    const store = mockStore({ dp: {} })
    await store.dispatch(actions.getDataPackage(
      'https://absolute.com/datapackage.json'
    ))
    let receivedResource = store.getActions()
    expect(0).toEqual(0) //replace with relative expect statements
  })

})
```

**Comment by anuveyatsu** [comment]
Tests should cover:
* support for differently specified data sources:
  * inline
  * relative path
  * URL
* support for different graph types:
  * vega-lite
  * plotly
* support for handsontable

**Comment by rufuspollock** [comment]
Much of this may end up as DUPLICATE or WONTFIX because:

* Covered in DP views refactor (view spec conversion) #97 
* Not needed as covered in datapackage-js (data source stuff)

**Comment by rufuspollock** [comment]
FIXED. As per previous comment largely fixed or duplicate. I'm marking this as fixed as we now have pretty reasonable tests as part of #97 and #106 .

Note: I'm leaving 3h here as we did spend some time on this.
