### ISSUE TITLE
[epic] DP Views - refactor and document

### ISSUE THREAD

**Issue by rufuspollock** [datopian/frontend-showcase-js#97]
The current implementation of Data Package views is messy and incomplete. For example:

* DP Views code is currently part of the DataPackageViewContainer
* Not clear what exactly is supported (i.e. what resources, what data sources, what graph specs such as vega, vega-lite). Clear gaps in support (e.g. vega / vega-lite are partial or incomplete, data sourcing is poorly defined)
* Not clear what parts are under test
* Intertwining of this with the work on redux and async loading of data packages (which turns out to be a whole area of its own!)

This reflects:

* Sprint to get this done originally and then react refactor
* Lack of precisely defined feature set. Specifically, that views spec is still in flux - in fact, we are using this implementation to decide on that views spec!

## Tasks

Analysis and documentation

* [x] Analyse current feature set and implementation against this - #83 - [resulting status sheet][sheet]
  * [x] Include some documentation of current "spec" as supported atm
* [x] Outline a Data Package Views specification based on our current implementation
  * In progress in [Data Package Views and DPR hackmd][hackmd]
* [x] Design and document technical architecture
  * In progress - see diagram below

[sheet]: https://docs.google.com/a/atomatic.net/spreadsheets/d/161rgtX3q34vIDbbfdCdvhBO_3sDX2tcp7iX9dI1Acj8/edit?usp=drive_web
[hackmd]: https://hackmd.io/JwEwjGDMCGBMsFoBsAWAHJBLhmggRgAzCbDDRkgCsAZgKaw35A==?both#

Code tasks

* [x] Factor all view spec handling out of React components into standalone library file
  * Note: we are not talking about the graph render - just spec generation
* [x] Add support for new DP views spec approach
  * [x] Basic refactor to simplify and make more understandable
  * [x] Recline conversion (to "Simple Graph Spec" form)
  * [x] Introduce normalization - ensure e.g. that there is a dataSource always present, set name 
  * [x] Data compilation from data source spec
  * [x] Generate Plotly spec for Recline (via generation of Simple Graph Spec or vega-lite spec if possible)
  * [x] HandsOnTable refactor

Finally, (and separately from this issue):

* Refactor existing Container code to use new views and new data load #109
* Note this has a dependency on refactoring data loading #106 

## Background

[DP Views Spec and Code Implementation doc][hackmd]

### Desired Features

[Implementation Status Spreadsheet][views-status]

[views-status]: https://docs.google.com/spreadsheets/d/161rgtX3q34vIDbbfdCdvhBO_3sDX2tcp7iX9dI1Acj8/edit#gid=0

Graph specs

* Recline
* Vega-lite
* Vega
* [Plotly]

Data sources for views

* Nothing specified (first resource)
* Resource
  * Inline
  * Relative path
  * FQ Urls: http://
* Resource data format
  * CSV
  * GeoJSON
* Several resources for one view
* Inline in view (?)

General Functionality

* Multiple views
* Table as a view

Data transformation (future)

* Filter
* Join (two resources)
* Pivot

### Data Package Views - Processing Structure

*In progress*

[Diagram Source](https://docs.google.com/drawings/d/1M_6Vcal4PPSHpuKpzJQGvRUbPb5yeaAdRHomIIbfnlY/edit)

<img src="https://docs.google.com/drawings/d/1M_6Vcal4PPSHpuKpzJQGvRUbPb5yeaAdRHomIIbfnlY/pub?w=790&h=1402" />

**Comment by rufuspollock** [comment]
FIXED. All done in src/utils/view.js and associated tests.

Note: did not do vega / vega-lite as not on critical path and needs some thought. Created an issue for this future work #107 

Follow up issues:

* Refactor existing Container code to use new views and new data load #109
  * Note this has a dependency on refactoring data loading #106
